export const FILTER_TYPE = {
  FEATURED: 0,
  LATEST: 1,
  MANAGER: 2,
  PART_TIME: 3,
  INTERN: 4,
  SUITABLE: 5,
  SALARY: 6,
  TOP: 7,
};

export const SALARY_DISPLAY_TYPE = {
  NO_SALARY: 0,
  NEGOTIABLE_SALARY: 1,
  DETAILED_SALARY: 2,
};

export const GENDER = {
  MALE: 0,
  FEMALE: 1,
  NOT_REQUIRE: 2,
};